spring:
  application:
    name: swop-api
  mandatory-file-encoding: utf-8
server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

web:
  swop-base-url: https://swop.cx
  api-key: { SWOP_API_TOKEN }

redis:
  url: redis://localhost:6379/0

management:
  health:
    influxdb:
      enabled: true

influx:
  bucket: swop-api-metrics
  token: { INFLUX_DB_TOKEN }
  org: swop-api
  uri: http://localhost:8086/
  user-name: admin
  password: password
